'use client';

import { Box } from "@mui/material";

import Cards from "@/components/dashboard/Cards";
import Header from "@/components/dashboard/Header";
import SelectedPatientsTable from "@/components/dashboard/SelectedPatientsTable";
import PatientList from "@/components/dashboard/PatientList";

import { Patient } from '@/types/patient';

// Mock data for demonstration
const mockPatients: Patient[] = [
  {
    id: '1',
    name: 'Richardson, Alan',
    gender: 'Male',
    insurance: 'Medicare',
    attributedClinic: 'Primary Care North',
    attributedPhysician: 'Dr. Nelson',
    lastAWV: '12/29/2020',
    ccmEleg: true,
    chronicConditions: ['Hypertension', 'Diabetes'],
    pmpmCost: 843.25,
    rafYtd: 1.197,
    rafVar: 0.12,
    hccGaps: 2,
    careGaps: 5,
    flagReasons: [
      { label: 'AWV Due', color: 'yellow' },
      { label: 'HCC Recapt', color: 'blue' },
    ],
  },
  {
    id: '2',
    name: 'Smith, Janet',
    gender: 'Female',
    insurance: 'Medicare Advantage',
    attributedClinic: 'Family Medicine East',
    attributedPhysician: 'Dr. Martinez',
    lastAWV: '12/29/2020',
    ccmEleg: false,
    chronicConditions: ['Hypertension', 'Heart Failure'],
    pmpmCost: 1054.62,
    rafYtd: 0.942,
    rafVar: -0.05,
    hccGaps: 0,
    careGaps: 2,
    flagReasons: [
      { label: 'Medication adherence', color: 'blue' },
    ],
  },
  {
    id: '3',
    name: 'Johnson, Robert',
    gender: 'Male',
    insurance: 'Commercial',
    attributedClinic: 'Primary Care South',
    attributedPhysician: 'Dr. Stevens',
    lastAWV: '12/29/2020',
    ccmEleg: true,
    chronicConditions: ['COPD', 'Diabetes'],
    pmpmCost: 725.48,
    rafYtd: 1.633,
    rafVar: 0.24,
    hccGaps: 1,
    careGaps: 4,
    flagReasons: [
      { label: 'ER Visit', color: 'red' },
      { label: 'Care Gaps', color: 'green' },
    ],
  },
  {
    id: '4',
    name: 'Williams, Mary',
    gender: 'Female',
    insurance: 'Medicare',
    attributedClinic: 'Senior Health Center',
    attributedPhysician: 'Dr. Nelson',
    lastAWV: '12/29/2020',
    ccmEleg: false,
    chronicConditions: ['Hypertension', 'Diabetes'],
    pmpmCost: 632.17,
    rafYtd: 0.852,
    rafVar: -0.10,
    hccGaps: 2,
    careGaps: 6,
    flagReasons: [
      { label: 'AWV Due', color: 'yellow' },
    ],
  },
  {
    id: '5',
    name: 'Brown, Michael',
    gender: 'Male',
    insurance: 'Medicare',
    attributedClinic: 'Primary Care North',
    attributedPhysician: 'Dr. Stevens',
    lastAWV: '12/29/2020',
    ccmEleg: false,
    chronicConditions: ['Heart Failure', 'COP'],
    pmpmCost: 1477.35,
    rafYtd: 2.023,
    rafVar: 0.35,
    hccGaps: 0,
    careGaps: 3,
    flagReasons: [
      { label: 'High Utilizer', color: 'red' },
    ],
  },
  // Additional mock patients for pagination
  {
    id: '6',
    name: 'Garcia, Maria',
    gender: 'Female',
    insurance: 'Medicaid',
    attributedClinic: 'Downtown Clinic',
    attributedPhysician: 'Dr. Patel',
    lastAWV: '01/15/2021',
    ccmEleg: true,
    chronicConditions: ['Asthma'],
    pmpmCost: 512.00,
    rafYtd: 1.120,
    rafVar: 0.10,
    hccGaps: 1,
    careGaps: 2,
    flagReasons: [
      { label: 'Care Gaps', color: 'green' },
    ],
  },
  {
    id: '7',
    name: 'Lee, David',
    gender: 'Male',
    insurance: 'Commercial',
    attributedClinic: 'Westside Health',
    attributedPhysician: 'Dr. Kim',
    lastAWV: '03/10/2021',
    ccmEleg: false,
    chronicConditions: ['Hypertension'],
    pmpmCost: 789.50,
    rafYtd: 1.010,
    rafVar: 0.05,
    hccGaps: 2,
    careGaps: 1,
    flagReasons: [
      { label: 'AWV Due', color: 'yellow' },
    ],
  },
  {
    id: '8',
    name: 'Nguyen, Linh',
    gender: 'Female',
    insurance: 'Medicare',
    attributedClinic: 'Family Medicine East',
    attributedPhysician: 'Dr. Martinez',
    lastAWV: '02/20/2021',
    ccmEleg: true,
    chronicConditions: ['Diabetes'],
    pmpmCost: 900.00,
    rafYtd: 1.200,
    rafVar: 0.08,
    hccGaps: 1,
    careGaps: 2,
    flagReasons: [
      { label: 'Medication adherence', color: 'blue' },
    ],
  },
  {
    id: '9',
    name: 'Patel, Anil',
    gender: 'Male',
    insurance: 'Medicare Advantage',
    attributedClinic: 'Downtown Clinic',
    attributedPhysician: 'Dr. Patel',
    lastAWV: '04/05/2021',
    ccmEleg: false,
    chronicConditions: ['COPD'],
    pmpmCost: 1100.00,
    rafYtd: 1.500,
    rafVar: 0.20,
    hccGaps: 0,
    careGaps: 3,
    flagReasons: [
      { label: 'ER Visit', color: 'red' },
    ],
  },
  {
    id: '10',
    name: 'Sanchez, Rosa',
    gender: 'Female',
    insurance: 'Medicaid',
    attributedClinic: 'Senior Health Center',
    attributedPhysician: 'Dr. Nelson',
    lastAWV: '05/12/2021',
    ccmEleg: true,
    chronicConditions: ['Hypertension', 'Asthma'],
    pmpmCost: 650.00,
    rafYtd: 0.980,
    rafVar: -0.02,
    hccGaps: 1,
    careGaps: 2,
    flagReasons: [
      { label: 'Care Gaps', color: 'green' },
    ],
  },
  {
    id: '11',
    name: 'Miller, John',
    gender: 'Male',
    insurance: 'Medicare',
    attributedClinic: 'Primary Care North',
    attributedPhysician: 'Dr. Nelson',
    lastAWV: '06/18/2021',
    ccmEleg: false,
    chronicConditions: ['Heart Failure'],
    pmpmCost: 1200.00,
    rafYtd: 1.800,
    rafVar: 0.30,
    hccGaps: 2,
    careGaps: 4,
    flagReasons: [
      { label: 'High Utilizer', color: 'red' },
    ],
  },
  {
    id: '12',
    name: 'Kim, Soo',
    gender: 'Female',
    insurance: 'Commercial',
    attributedClinic: 'Westside Health',
    attributedPhysician: 'Dr. Kim',
    lastAWV: '07/22/2021',
    ccmEleg: true,
    chronicConditions: ['Diabetes', 'Asthma'],
    pmpmCost: 980.00,
    rafYtd: 1.350,
    rafVar: 0.15,
    hccGaps: 1,
    careGaps: 2,
    flagReasons: [
      { label: 'AWV Due', color: 'yellow' },
      { label: 'Care Gaps', color: 'green' },
    ],
  },
  {
    id: '13',
    name: 'White, Susan',
    gender: 'Female',
    insurance: 'Medicare Advantage',
    attributedClinic: 'Family Medicine East',
    attributedPhysician: 'Dr. Martinez',
    lastAWV: '08/30/2021',
    ccmEleg: false,
    chronicConditions: ['Hypertension'],
    pmpmCost: 700.00,
    rafYtd: 1.000,
    rafVar: 0.00,
    hccGaps: 0,
    careGaps: 1,
    flagReasons: [
      { label: 'Medication adherence', color: 'blue' },
    ],
  },
  {
    id: '14',
    name: 'Davis, Mark',
    gender: 'Male',
    insurance: 'Medicaid',
    attributedClinic: 'Downtown Clinic',
    attributedPhysician: 'Dr. Patel',
    lastAWV: '09/14/2021',
    ccmEleg: true,
    chronicConditions: ['COPD', 'Asthma'],
    pmpmCost: 850.00,
    rafYtd: 1.250,
    rafVar: 0.12,
    hccGaps: 1,
    careGaps: 3,
    flagReasons: [
      { label: 'ER Visit', color: 'red' },
    ],
  },
  {
    id: '15',
    name: 'Lopez, Ana',
    gender: 'Female',
    insurance: 'Medicare',
    attributedClinic: 'Senior Health Center',
    attributedPhysician: 'Dr. Nelson',
    lastAWV: '10/05/2021',
    ccmEleg: false,
    chronicConditions: ['Hypertension', 'Diabetes'],
    pmpmCost: 950.00,
    rafYtd: 1.100,
    rafVar: 0.09,
    hccGaps: 2,
    careGaps: 2,
    flagReasons: [
      { label: 'AWV Due', color: 'yellow' },
    ],
  },
];

export default function Dashboard() {
  // Render
  return (
    <Box>
      <Header />
      <Box sx={{
        p: 3,
      }}>
        <Cards />
        <SelectedPatientsTable onTableSelect={() => { }} />
        <PatientList patients={mockPatients} />
      </Box>
    </Box>
  );
}
